"""Ruleset registry for supported D&D-like 5e content."""

from rules.registry import (
    DEFAULT_RULESET_CONFIG_PATH,
    DEFAULT_RULESET_NAME,
    RulesetRegistry,
    create_default_registry,
    get_active_ruleset,
    get_registry,
    get_unsupported_reason,
    is_supported_content,
    load_ruleset_from_yaml,
)
from rules.progression import (
    MAX_SUPPORTED_LEVEL,
    MIN_SUPPORTED_LEVEL,
    PROFICIENCY_BONUS_BY_LEVEL,
    XP_THRESHOLDS,
    apply_level_up,
    build_class_features,
    build_class_resources,
    can_level_up,
    get_level_for_xp,
    get_proficiency_bonus,
    is_spellcaster,
    spell_slots_for_level,
    sync_character_progression,
)
from rules.races import (
    CUSTOM_RACE,
    SUPPORTED_RACES,
    RaceDefinition,
    get_race_definition,
    is_supported_race,
)
from rules.ruleset import Ruleset

__all__ = [
    "DEFAULT_RULESET_CONFIG_PATH",
    "DEFAULT_RULESET_NAME",
    "MAX_SUPPORTED_LEVEL",
    "MIN_SUPPORTED_LEVEL",
    "PROFICIENCY_BONUS_BY_LEVEL",
    "CUSTOM_RACE",
    "SUPPORTED_RACES",
    "RaceDefinition",
    "Ruleset",
    "RulesetRegistry",
    "XP_THRESHOLDS",
    "apply_level_up",
    "build_class_features",
    "build_class_resources",
    "can_level_up",
    "create_default_registry",
    "get_active_ruleset",
    "get_level_for_xp",
    "get_proficiency_bonus",
    "get_race_definition",
    "get_registry",
    "get_unsupported_reason",
    "is_supported_content",
    "is_spellcaster",
    "is_supported_race",
    "load_ruleset_from_yaml",
    "spell_slots_for_level",
    "sync_character_progression",
]
