"""Ruleset registry for supported D&D-like 5e content."""

from rules.registry import (
    DEFAULT_RULESET_CONFIG_PATH,
    DEFAULT_RULESET_NAME,
    RulesetRegistry,
    create_default_registry,
    get_active_ruleset,
    get_registry,
    get_unsupported_reason,
    is_supported_content,
    load_ruleset_from_yaml,
)
from rules.progression import (
    MAX_SUPPORTED_LEVEL,
    MIN_SUPPORTED_LEVEL,
    PROFICIENCY_BONUS_BY_LEVEL,
    XP_THRESHOLDS,
    apply_level_up,
    build_class_features,
    build_class_resources,
    can_level_up,
    get_level_for_xp,
    get_proficiency_bonus,
    is_spellcaster,
    spell_slots_for_level,
    sync_character_progression,
)
from rules.classes import (
    CLASS_DEFINITIONS,
    ClassDefinition,
    build_class_features as build_class_features_from_definitions,
    class_uses_spellcasting,
    get_class_definition,
    get_supported_class_definitions,
    get_supported_subclass_definitions,
    spellcasting_ability_for_class,
    spellcasting_type_for_class,
    spell_slots_for_class_level,
)
from rules.classes.cleric import CLERIC_DEFINITION
from rules.classes.fighter import FIGHTER_DEFINITION, FIGHTING_STYLE_OPTIONS
from rules.classes.wizard import WIZARD_DEFINITION
from rules.subclasses import (
    SUBCLASS_DEFINITIONS,
    SubclassDefinition,
    get_subclass_definition,
    get_subclasses_for_class,
)
from rules.subclasses.champion import CHAMPION_DEFINITION
from rules.subclasses.evocation import EVOCATION_DEFINITION
from rules.subclasses.life_domain import LIFE_DOMAIN_DEFINITION
from combat.class_features import FeatureDefinition
from rules.feats import (
    ABILITY_SCORE_IMPROVEMENT_NAME,
    COMBAT_HOOK_NAMES,
    FEAT_DEFINITIONS,
    GRAPPLER_NAME,
    FeatDefinition,
    get_feat_definition,
    get_feat_prerequisite_failures,
    get_supported_feat_definitions,
    get_unsupported_feat_reason,
    is_feat_supported,
    normalize_ability_name,
    validate_feat_prerequisites,
)
from rules.races import (
    CUSTOM_RACE,
    SUPPORTED_RACES,
    RaceDefinition,
    get_race_definition,
    is_supported_race,
)
from rules.ruleset import Ruleset
from rules.spellcasting_progression import (
    FULL_CASTER,
    FULL_CASTER_SPELL_SLOTS,
    SPELLCASTING_TYPES,
    class_uses_spellcasting_progression,
    get_max_spell_level_for_progression,
    get_spell_slots_for_progression,
    get_spellcasting_ability_for_class,
    get_spellcasting_type_for_class,
)

__all__ = [
    "DEFAULT_RULESET_CONFIG_PATH",
    "DEFAULT_RULESET_NAME",
    "ABILITY_SCORE_IMPROVEMENT_NAME",
    "COMBAT_HOOK_NAMES",
    "FEAT_DEFINITIONS",
    "FIGHTER_DEFINITION",
    "FIGHTING_STYLE_OPTIONS",
    "FULL_CASTER",
    "FULL_CASTER_SPELL_SLOTS",
    "GRAPPLER_NAME",
    "CLASS_DEFINITIONS",
    "CHAMPION_DEFINITION",
    "CLERIC_DEFINITION",
    "EVOCATION_DEFINITION",
    "MAX_SUPPORTED_LEVEL",
    "MIN_SUPPORTED_LEVEL",
    "PROFICIENCY_BONUS_BY_LEVEL",
    "CUSTOM_RACE",
    "SUPPORTED_RACES",
    "RaceDefinition",
    "ClassDefinition",
    "FeatureDefinition",
    "FeatDefinition",
    "Ruleset",
    "RulesetRegistry",
    "LIFE_DOMAIN_DEFINITION",
    "SPELLCASTING_TYPES",
    "SUBCLASS_DEFINITIONS",
    "SubclassDefinition",
    "XP_THRESHOLDS",
    "WIZARD_DEFINITION",
    "apply_level_up",
    "build_class_features",
    "build_class_features_from_definitions",
    "build_class_resources",
    "can_level_up",
    "class_uses_spellcasting",
    "class_uses_spellcasting_progression",
    "create_default_registry",
    "get_active_ruleset",
    "get_class_definition",
    "get_feat_definition",
    "get_feat_prerequisite_failures",
    "get_level_for_xp",
    "get_proficiency_bonus",
    "get_max_spell_level_for_progression",
    "get_race_definition",
    "get_registry",
    "get_spell_slots_for_progression",
    "get_spellcasting_ability_for_class",
    "get_subclass_definition",
    "get_subclasses_for_class",
    "get_supported_feat_definitions",
    "get_supported_class_definitions",
    "get_supported_subclass_definitions",
    "get_unsupported_reason",
    "get_unsupported_feat_reason",
    "is_feat_supported",
    "is_supported_content",
    "is_spellcaster",
    "is_supported_race",
    "load_ruleset_from_yaml",
    "normalize_ability_name",
    "spell_slots_for_level",
    "spellcasting_ability_for_class",
    "spellcasting_type_for_class",
    "get_spellcasting_type_for_class",
    "spell_slots_for_class_level",
    "sync_character_progression",
    "validate_feat_prerequisites",
]
