"""Combat simulation primitives."""

from combat.action_economy import ActionEconomy, reset_turn_resources
from combat.abilities import Ability, SpellAbility, WeaponAttack, ability_modifier
from combat.actions import (
    COMMON_ACTION_ATTACK,
    COMMON_ACTION_CAST_SPELL,
    COMMON_ACTION_DASH,
    COMMON_ACTION_DISENGAGE,
    COMMON_ACTION_DODGE,
    COMMON_ACTION_END_TURN,
    COMMON_ACTION_GRAPPLE,
    COMMON_ACTION_HELP,
    COMMON_ACTION_HIDE,
    COMMON_ACTION_IMPROVISED,
    COMMON_ACTION_MOVE,
    COMMON_ACTION_READY,
    COMMON_ACTION_SEARCH,
    COMMON_ACTION_SHOVE,
    COMMON_ACTION_STABILIZE,
    COMMON_ACTION_USE_OBJECT,
    ActionResult,
    AttackAction,
    CastSpellAction,
    CombatAction,
    DashAction,
    DisengageAction,
    DodgeAction,
    EndTurnAction,
    GrappleAction,
    HelpAction,
    HideAction,
    ImprovisedAction,
    MoveAction,
    ReadyAction,
    SearchAction,
    ShoveAction,
    StabilizeAction,
    UseObjectAction,
)
from combat.class_features import ClassFeature, Resource, reset_resources
from combat.environment import CombatEnvironment
from combat.encounter_generator import EncounterGenerator
from combat.map import GridMap
from combat.models import (
    Character,
    CombatState,
    Condition,
    Enemy,
    Position,
    Stats,
    Team,
)
from combat.presets import (
    FighterArcher,
    FighterChampionGreatsword,
    Goblin,
    Orc,
    create_test_encounter,
)
from combat.rewards import (
    CombatReward,
    CombatRewardSnapshot,
    RewardConfig,
    calculate_combat_reward,
    opposing_team,
    snapshot_combat_state,
)

__all__ = [
    "Ability",
    "ActionEconomy",
    "ActionResult",
    "AttackAction",
    "COMMON_ACTION_ATTACK",
    "COMMON_ACTION_CAST_SPELL",
    "COMMON_ACTION_DASH",
    "COMMON_ACTION_DISENGAGE",
    "COMMON_ACTION_DODGE",
    "COMMON_ACTION_END_TURN",
    "COMMON_ACTION_GRAPPLE",
    "COMMON_ACTION_HELP",
    "COMMON_ACTION_HIDE",
    "COMMON_ACTION_IMPROVISED",
    "COMMON_ACTION_MOVE",
    "COMMON_ACTION_READY",
    "COMMON_ACTION_SEARCH",
    "COMMON_ACTION_SHOVE",
    "COMMON_ACTION_STABILIZE",
    "COMMON_ACTION_USE_OBJECT",
    "CastSpellAction",
    "Character",
    "ClassFeature",
    "CombatAction",
    "CombatEnvironment",
    "CombatReward",
    "CombatRewardSnapshot",
    "CombatState",
    "Condition",
    "DashAction",
    "DisengageAction",
    "DodgeAction",
    "Enemy",
    "EndTurnAction",
    "EncounterGenerator",
    "FighterArcher",
    "FighterChampionGreatsword",
    "Goblin",
    "GrappleAction",
    "GridMap",
    "HelpAction",
    "HideAction",
    "ImprovisedAction",
    "MoveAction",
    "Orc",
    "Position",
    "ReadyAction",
    "RewardConfig",
    "Resource",
    "SearchAction",
    "ShoveAction",
    "StabilizeAction",
    "UseObjectAction",
    "ability_modifier",
    "calculate_combat_reward",
    "create_test_encounter",
    "opposing_team",
    "reset_turn_resources",
    "reset_resources",
    "SpellAbility",
    "snapshot_combat_state",
    "Stats",
    "Team",
    "WeaponAttack",
]
