"""Character model compatibility exports."""

from combat.models import (
    Character,
    CombatState,
    Condition,
    Enemy,
    Position,
    Stats,
    Team,
)
from rules.progression import (
    XP_THRESHOLDS,
    apply_level_up,
    can_level_up,
    get_level_for_xp,
    get_proficiency_bonus,
    sync_character_progression,
)
from rules.xp import (
    CR_XP_TABLE,
    award_party_xp,
    calculate_encounter_xp,
    get_xp_for_cr,
)
from combat.features import (
    AbilityScoreImprovement,
    add_feat,
    apply_ability_score_improvement,
    apply_level_four_choice,
    can_choose_asi_or_feat,
    character_has_feat,
    get_supported_feats_for_builder,
)
from combat.character_builder import (
    CharacterBuildRequest,
    build_character,
    supported_class_options,
    supported_item_options,
    supported_subclass_options,
    validate_class_selection,
    validate_item_selection,
)
from combat.inventory import (
    Bomb,
    HealerKit,
    PotionOfHealing,
    add_item,
    available_inventory_items,
    get_item_definition,
    get_supported_item_definitions,
    resolve_inventory_items,
)
from combat.items import ItemActionCost, ItemDefinition, ItemEffect, ItemTargetType
from combat.race_traits import (
    RaceTraits,
    apply_race_traits,
    has_damage_resistance,
    weapon_is_racially_proficient,
)

__all__ = [
    "Character",
    "CharacterBuildRequest",
    "CombatState",
    "Condition",
    "Enemy",
    "Position",
    "RaceTraits",
    "Stats",
    "Team",
    "CR_XP_TABLE",
    "XP_THRESHOLDS",
    "AbilityScoreImprovement",
    "Bomb",
    "HealerKit",
    "ItemActionCost",
    "ItemDefinition",
    "ItemEffect",
    "ItemTargetType",
    "PotionOfHealing",
    "add_item",
    "add_feat",
    "apply_ability_score_improvement",
    "apply_level_four_choice",
    "apply_level_up",
    "apply_race_traits",
    "award_party_xp",
    "available_inventory_items",
    "build_character",
    "can_choose_asi_or_feat",
    "can_level_up",
    "calculate_encounter_xp",
    "character_has_feat",
    "get_level_for_xp",
    "get_item_definition",
    "get_proficiency_bonus",
    "get_xp_for_cr",
    "get_supported_item_definitions",
    "get_supported_feats_for_builder",
    "has_damage_resistance",
    "supported_class_options",
    "supported_item_options",
    "supported_subclass_options",
    "sync_character_progression",
    "validate_class_selection",
    "validate_item_selection",
    "weapon_is_racially_proficient",
    "resolve_inventory_items",
]
