"""Russian UI labels for internal combat/rules names."""

from __future__ import annotations

import re


LABELS: dict[str, str] = {
    "PLAYERS": "Игроки",
    "ENEMIES": "Враги",
    "players": "Игроки",
    "enemies": "Враги",
    "Movement": "Перемещение",
    "Main Action": "Основное действие",
    "Attack Abilities": "Атакующие способности",
    "Spells": "Заклинания",
    "Inventory": "Инвентарь",
    "Bonus Action": "Бонусное действие",
    "Reaction": "Реакция",
    "End Turn": "Конец хода",
    "Move": "Перемещение",
    "Attack": "Атака",
    "Cast Spell": "Заклинание",
    "Dash": "Рывок",
    "Disengage": "Отход",
    "Dodge": "Уклонение",
    "Help": "Помощь",
    "Hide": "Скрыться",
    "Use Object": "Использовать предмет",
    "Ready": "Подготовить действие",
    "Grapple": "Захват",
    "Shove": "Толчок",
    "Shove Prone": "Толчок: сбить с ног",
    "Shove Push": "Толчок: оттолкнуть",
    "Opportunity Attack": "Провоцированная атака",
    "EndTurn": "Завершить ход",
    "MoveAction": "Перемещение",
    "AttackAction": "Атака",
    "CastSpellAction": "Заклинание",
    "DashAction": "Рывок",
    "DisengageAction": "Отход",
    "DodgeAction": "Уклонение",
    "HelpAction": "Помощь",
    "HideAction": "Скрыться",
    "UseObjectAction": "Предмет",
    "ReadyAction": "Подготовка",
    "GrappleAction": "Захват",
    "ShoveAction": "Толчок",
    "EndTurnAction": "Конец хода",
    "SecondWindAction": "Второе дыхание",
    "ActionSurgeAction": "Всплеск действий",
    "Spell:": "Заклинание:",
    "Item:": "Предмет:",
    "Class Feature:": "Классовая способность:",
    "slot": "ячейка",
    "Second Wind": "Второе дыхание",
    "Action Surge": "Всплеск действий",
    "Preserve Life": "Сохранение жизни",
    "Channel Divinity": "Божественный канал",
    "Arcane Recovery": "Магическое восстановление",
    "Fire Bolt": "Огненный снаряд",
    "Ray of Frost": "Луч холода",
    "Magic Missile": "Волшебная стрела",
    "Shield": "Щит",
    "Burning Hands": "Пылающие ладони",
    "Scorching Ray": "Палящий луч",
    "Fireball": "Огненный шар",
    "Sacred Flame": "Священное пламя",
    "Cure Wounds": "Лечение ран",
    "Healing Word": "Исцеляющее слово",
    "Guiding Bolt": "Направляющий снаряд",
    "Bless": "Благословение",
    "Spare the Dying": "Уход за умирающим",
    "Potion of Healing": "Зелье лечения",
    "Alchemist Fire": "Алхимический огонь",
    "Bomb": "Бомба",
    "HealerKit": "Набор лекаря",
    "Healer Kit": "Набор лекаря",
    "Longsword": "Длинный меч",
    "Greatsword": "Двуручный меч",
    "Greataxe": "Секира",
    "Shortbow": "Короткий лук",
    "Longbow": "Длинный лук",
    "Light Crossbow": "Лёгкий арбалет",
    "Dagger": "Кинжал",
    "Quarterstaff": "Боевой посох",
    "Mace": "Булава",
    "Claws": "Когти",
    "Bite": "Укус",
    "MELEE_DAMAGE": "Ближний урон",
    "RANGED_DAMAGE": "Дальний урон",
    "TANK": "Защитник",
    "SUPPORT": "Поддержка",
    "CASTER": "Заклинатель",
    "BRUTE_ENEMY": "Грубая сила",
    "SKIRMISHER_ENEMY": "Налётчик",
    "Human": "Человек",
    "Dwarf": "Дварф",
    "Elf": "Эльф",
    "Halfling": "Полурослик",
    "Goblin Melee": "Гоблин-рукопашник",
    "Goblin Archer": "Гоблин-лучник",
    "Goblin": "Гоблин",
    "Orc Warrior": "Орк-воин",
    "Orc": "Орк",
    "Skeleton Archer": "Скелет-лучник",
    "Bandit": "Бандит",
    "Wolf": "Волк",
    "Fire Elemental": "Огненный элементаль",
    "Fire Elemental Simple": "Огненный элементаль",
    "FireElementalSimple": "Огненный элементаль",
    "open_field": "Открытое поле",
    "cover_arena": "Арена с укрытиями",
    "difficult_terrain_pass": "Перевал со сложной местностью",
    "obstacle_corridor": "Коридор с препятствиями",
    "Fighter Level 1 Basic": "Воин 1 уровня",
    "Fighter Champion Greatsword": "Воин-чемпион с двуручным мечом",
    "Fighter Champion Archer": "Воин-чемпион лучник",
    "Cleric Life Support": "Жрец Домена Жизни",
    "Wizard Evoker": "Волшебник-воплотитель",
    "Fighter": "Воин",
    "Cleric": "Жрец",
    "Wizard": "Волшебник",
    "Champion": "Чемпион",
    "Life Domain": "Домен Жизни",
    "School of Evocation": "Школа Воплощения",
    "prone": "лежит",
    "grappled": "в захвате",
    "hidden": "скрыт",
    "dodging": "уклоняется",
    "disengaged": "отошёл",
    "stable": "стабилен",
}

LOG_REPLACEMENTS = (
    ("Policy selected an illegal action", "Политика выбрала недопустимое действие"),
    ("selected an illegal action", "выбрала недопустимое действие"),
    ("has no melee weapon for opportunity attack", "не имеет оружия ближнего боя для провоцированной атаки"),
    ("has no Action Surge uses remaining", "не имеет зарядов Всплеска действий"),
    ("to player party after victory", "отряду игроков за победу"),
    ("Combat has no living actors", "в бою нет живых участников"),
    ("actor or target not found", "участник или цель не найдены"),
    ("No item effect is implemented", "Эффект предмета не реализован"),
    ("cannot stand up from prone", "не может встать из положения лёжа"),
    ("has no available weapon attack", "не имеет доступной атаки оружием"),
    ("has no available spell", "не имеет доступного заклинания"),
    ("uses Channel Divinity", "использует Божественный канал"),
    ("uses Second Wind", "использует Второе дыхание"),
    ("uses Action Surge", "использует Всплеск действий"),
    ("cannot opportunity attack", "не может выполнить провоцированную атаку"),
    ("opportunity attacks", "выполняет провоцированную атаку"),
    ("Opportunity attacks", "Провоцированные атаки"),
    ("cannot attack missing target", "не может атаковать отсутствующую цель"),
    ("cannot Use an Object", "не может использовать предмет"),
    ("cannot Help now", "сейчас не может помочь"),
    ("Second Wind failed", "Второе дыхание не удалось"),
    ("Action Surge failed", "Всплеск действий не удался"),
    ("Preserve Life failed", "Сохранение жизни не удалось"),
    ("Use object failed", "Предмет не удалось использовать"),
    ("Cast spell failed", "Заклинание не удалось"),
    ("End turn failed", "Завершение хода не удалось"),
    ("Combat is already done", "Бой уже завершён"),
    ("Combat is done", "Бой завершён"),
    ("AI action error", "Ошибка действия ИИ"),
    ("Manual action error", "Ошибка ручного действия"),
    ("Selected action", "Выбранное действие"),
    ("target already defeated", "цель уже побеждена"),
    ("is not valid for", "недоступно для"),
    ("cannot end turn", "не может завершить ход"),
    ("cannot move to", "не может переместиться в"),
    ("cannot attack", "не может атаковать"),
    ("cannot target", "не может выбрать цель для"),
    ("cannot place", "не может выбрать область для"),
    ("cannot cast", "не может произнести"),
    ("cannot use", "не может использовать"),
    ("Move failed", "Перемещение не удалось"),
    ("Attack failed", "Атака не удалась"),
    ("Dash failed", "Рывок не удался"),
    ("Disengage failed", "Отход не удался"),
    ("Dodge failed", "Уклонение не удалось"),
    ("Help failed", "Помощь не удалась"),
    ("Hide failed", "Скрытие не удалось"),
    ("Ready failed", "Подготовка действия не удалась"),
    ("Grapple failed", "Захват не удался"),
    ("Shove failed", "Толчок не удался"),
    ("Stabilize failed", "Стабилизация не удалась"),
    ("uses Dash", "использует Рывок"),
    ("Movement remaining", "Осталось перемещения"),
    ("Movement spent", "Потрачено перемещение"),
    ("movement remaining", "перемещения осталось"),
    ("moves from", "перемещается из"),
    ("to Position", "в Position"),
    ("attempts to Hide", "пытается скрыться"),
    ("attempts to Grapple", "пытается захватить"),
    ("attempts to Shove", "пытается толкнуть"),
    ("and succeeds", "и преуспевает"),
    ("and fails", "и проваливает проверку"),
    ("critical hit", "критическое попадание"),
    ("Total damage", "Итого урона"),
    ("after save", "после спасброска"),
    ("Action spent", "Действие потрачено"),
    ("action_available", "действие доступно"),
    ("bonus_action_available", "бонусное действие доступно"),
    ("reaction_available", "реакция доступна"),
    ("uses Help", "помогает"),
    ("and heals", "и лечит"),
    ("prepared action", "подготовленное действие"),
    ("Initiative order", "Порядок инициативы"),
    ("rolls initiative", "бросает инициативу"),
    ("Active actor", "Активный участник"),
    ("starts turn", "начинает ход"),
    ("skips turn", "пропускает ход"),
    ("is incapacitated", "недееспособен"),
    ("is dead", "мёртв"),
    ("main_action_type", "тип действия"),
    ("action_category", "категория действия"),
    ("target_index", "индекс цели"),
    ("move_index", "индекс клетки"),
    ("option_index", "индекс варианта"),
    ("Disengages", "отходит"),
    ("Dodges", "уклоняется"),
    ("Awarded", "Начислено"),
    ("Winner", "Победитель"),
    ("Actor", "Участник"),
    ("ends turn", "завершает ход"),
    ("not found", "не найден"),
    ("missing", "отсутствует"),
    ("casts", "произносит"),
    ("at level", "уровнем"),
    ("stabilizes", "стабилизирует"),
    ("prepares", "подготавливает"),
    ("succeeds", "успех"),
    ("fails", "провал"),
    ("best of", "лучший из"),
    ("remaining", "осталось"),
    ("damage", "урон"),
    ("healing", "лечение"),
    ("heals", "лечит"),
    ("modifier", "модификатор"),
    ("attacks", "атакует"),
    ("attack", "атака"),
    ("miss", "промах"),
    ("hit", "попадание"),
    ("target", "цель"),
    ("actor", "участник"),
    ("trigger", "триггер"),
    ("Round", "Раунд"),
    ("begins", "начинается"),
    ("dead", "мёртв"),
    ("incapacitated", "недееспособен"),
    ("failed", "провалил"),
    ("succeeded", "успешно прошёл"),
    ("Opportunity attack", "Провоцированная атака"),
    ("spends", "тратит"),
    ("restores", "восстанавливает"),
    ("uses", "использует"),
    ("save", "спасбросок"),
    ("with", "с"),
    ("for", "на"),
    ("slot", "ячейка"),
    ("d20", "к20"),
    ("DEX", "ЛОВ"),
    ("CON", "ТЕЛ"),
    ("AC", "КД"),
    ("HP", "ОЗ"),
    ("XP", "опыта"),
    ("AI", "ИИ"),
    ("none", "нет"),
)


def ru_label(value: object) -> str:
    """Return a Russian display label for a known internal value."""

    text = str(value)
    return LABELS.get(text, text)


def ru_sentence(text: object) -> str:
    """Translate common fragments inside action labels."""

    result = str(text)
    for source, target in sorted(LABELS.items(), key=lambda item: len(item[0]), reverse=True):
        result = result.replace(source, target)
    return result


def translate_battle_log(text: object) -> str:
    """Translate common combat-engine log fragments for GUI display."""

    result = ru_sentence(text)
    result = re.sub(r"target (\d+)", r"цель \1", result)
    result = re.sub(r"slot (\d+)", r"ячейка \1", result)
    result = re.sub(r"AC (\d+)", r"КД \1", result)
    result = re.sub(r"vs КД", "против КД", result)
    result = re.sub(r"for ([\d-]+) урон", r"на \1 урона", result)
    result = re.sub(r"for ([\d-]+) damage", r"на \1 урона", result)
    result = re.sub(
        r"Position\(x=([-\d]+), y=([-\d]+)\)",
        r"клетка(\1, \2)",
        result,
    )
    for source, target in sorted(LOG_REPLACEMENTS, key=lambda item: len(item[0]), reverse=True):
        result = result.replace(source, target)
    result = ru_sentence(result)
    result = result.replace("True", "да").replace("False", "нет")
    return result
